pimcore_data_hub:
    configurations:
        DataObjectsImporter:
            general:
                active: true
                type: dataImporterDataObject
                name: DataObjectsImporter
                description: ''
                group: ''
                path: null
                modificationDate: 1658728636
                createDate: 1658389199
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: DataObjectsImporter/upload.import
            interpreterConfig:
                type: csv
                settings:
                    delimiter: ;
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '46'
                loadingStrategy:
                    type: id
                    settings:
                        dataSourceIndex: '0'
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: sequential
                idDataIndex: '0'
                cleanup:
                    strategy: delete
            mappingConfig:
                -
                    label: Model
                    dataSourceIndex:
                        - '1'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: model
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Project No'
                    dataSourceIndex:
                        - '2'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: project_no
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Tech Conditions'
                    dataSourceIndex:
                        - '3'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: tu
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Car Name'
                    dataSourceIndex:
                        - '8'
                        - '1'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: car_name
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    settings:
                        glue: '  модель '
                    transformationPipeline:
                        -
                            settings:
                                glue: '  модель '
                            type: combine
                -
                    label: Manufactorer
                    dataSourceIndex:
                        - '11'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: factory
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Bogie Type'
                    dataSourceIndex:
                        - '12'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: bogie_id
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Model ID'
                    dataSourceIndex:
                        - '0'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: model_id
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: 'Gauge width'
                    dataSourceIndex:
                        - '9'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: gauge1
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: 'Gauge 2'
                    dataSourceIndex:
                        - '10'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: gauge2
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: 'Num Axis'
                    dataSourceIndex:
                        - '14'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: num_axis
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: 'Max Speed'
                    dataSourceIndex:
                        - '19'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: max_speed
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: Carrying
                    dataSourceIndex:
                        - '22'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: carrying
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: Volume
                    dataSourceIndex:
                        - '23'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: volume
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: 'Start Year'
                    dataSourceIndex:
                        - '43'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: start_year
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: 'End Year'
                    dataSourceIndex:
                        - '44'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: end_yea
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: 'Record ID'
                    dataSourceIndex:
                        - '8'
                        - '1'
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: key
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    settings:
                        glue: ' '
                    transformationPipeline:
                        -
                            settings:
                                glue: ' '
                            type: combine
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: '24-07-2022 20:58'
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
