version: '3.5'

services:
    redis:
        image: redis:alpine

    db:
        image: mariadb:10.7
        ports:
            - "3306:3306"
        working_dir: /application
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-per-table=1]
        volumes:
            - pimcore-database:/var/lib/mysql
        env_file:
            - .env

    nginx:
        image: nginx:stable-alpine
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html:ro
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php-fpm
            - php-fpm-debug

    php-fpm:
        user: '1000:1000'
        image: pimcore/pimcore:PHP8.1-fpm
        container_name: php-beauty_php-fpm
        environment:
            COMPOSER_HOME: /var/www/html
        env_file:
            - .env
        depends_on:
            - db
        volumes:
            - .:/var/www/html
            - pimcore-tmp-storage:/tmp

    php-fpm-debug:
        user: '1000:1000'
        image: pimcore/pimcore:PHP8.1-fpm-debug
        depends_on:
            - db
        volumes:
            - .:/var/www/html
            - pimcore-tmp-storage:/tmp
        environment:
            PHP_IDE_CONFIG: serverName=localhost
            COMPOSER_HOME: /var/www/html

    supervisord:
        user: '1000:1000'
        image: pimcore/pimcore:PHP8.1-supervisord
        depends_on:
            - db
        volumes:
            - .:/var/www/html
            - ./.docker/supervisord.conf:/etc/supervisor/conf.d/pimcore.conf:ro


    elasticsearch:
        user: '1000:1000'
        image: elasticsearch:8.2.3
        container_name: elasticsearch
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
        depends_on:
            - php-fpm
    cron:
          build: ../docker-files/cron/
          restart: always
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
          depends_on:
             - php-fpm

    varnish:
          build: ../docker-files/varnish/
          ports:
            - "80:80"
          depends_on:
            - nginx

volumes:
    pimcore-database:
    pimcore-tmp-storage:
    elasticsearch-data:
